server:
  port: 8076
spring:
  application:
    name: forsrc-springboot-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/forsrc/MySpringBoot/
          search-paths: forsrc-springboot-config-repo
          username:
          password: