server:
  port: 8091
#management:
#  port: 9091
#  context-path: /mgt
spring:
  application:
    name: forsrc-springcloud-hystrix
  cloud:
    loadbalancer:
      retry:
        enabled: true


turbine:
  app-config: forsrc-springcloud-hystrix
  aggregator:
    clusterConfig: clusterturbine
  cluster-name-expression: metadata['cluster']


eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8078/eureka/
#  instance:
#    hostname: localhost
#    metadata-map:
#      management:
#        port: ${management.port}
#        context-path: ${management.context-path}
#      health:
#        path: ${management.context-path}/health
#    status-page-url-path: ${management.context-path}/info
#    health-check-url-path: ${management.context-path}/health
