server:
  port: 9071
spring:
  application:
    name: forsrc-springcloud-eureka-client
  cloud:
    config:
      profile: dev
      label: master
      discovery:
        enabled: true
        serviceId: forsrc-springcloud-eureka-client
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8078/eureka/
